<template>
    <font-awesome-icon
        :icon="icon"
        :size="size"
        :class="classNames"
        :spin="spin"
    />
</template>

<script>
    import { library } from '@fortawesome/fontawesome-svg-core';
    import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
    import {
        faPlus,
        faInfoCircle,
        faTrashAlt,
        faSpinner,
        faDownload,
        faQuestionCircle,
        faCheckCircle,
        faPlusCircle,
        faCheck,
        faEnvelope,
        faUser,
        faInfo,
        faSync,
        faEye,
        faEyeSlash,
        faCopy,
        faChartLine,
        faBell,
        faBellSlash,
        faLock,
        faComment,
        faAlignLeft,
        faAngleDown,
        faAngleRight,
        faAngleLeft,
        faArrowLeft,
        faArrowRight,
        faArrowUp,
        faArrowDown,
        faArrowsAltH,
        faAd,
        faBan,
        faBookmark,
        faBriefcase,
        faBullhorn,
        faCaretDown,
        faCaretLeft,
        faCaretRight,
        faCaretUp,
        faChartBar,
        faCheckSquare,
        faChevronUp,
        faChevronDown,
        faChevronRight,
        faChevronLeft,
        faCircle,
        faCreditCard,
        faCog,
        faCogs,
        faCompressAlt,
        faCrosshairs,
        faDatabase,
        faDotCircle,
        faEdit,
        faEllipsisH,
        faExclamation,
        faExclamationCircle,
        faExclamationTriangle,
        faExpandAlt,
        faExternalLinkAlt,
        faEquals,
        faGlobe,
        faKey,
        faLayerGroup,
        faMinus,
        faPlayCircle,
        faPlug,
        faPlusSquare,
        faQuestion,
        faRocket,
        faSearch,
        faSignOutAlt,
        faSlash,
        faStar,
        faTimes,
        faTimesCircle,
        faUsersCog,
        faUpload,
        faListOl,
        faFileImage,
        faCalendar,
        faCalendarAlt,
        faCamera,
        faShareAlt,
        faShieldAlt,
        faMobileAlt,
        faMoneyBillAlt,
        faClock,
        faCodeBranch,
        faFile,
        faFileAlt,
        faImage,
        faLink,
        faDollarSign,
        faStickyNote,
        faIdBadge,
        faTh,
        faTextWidth,
        faIdCard,
        faAngleDoubleUp,
        faDraftingCompass,
        faGraduationCap,
        faChartArea,
        faTag,
        faTrash,
        faBars,
        faRedo,
        faVideo,
        faBook,
    } from '@fortawesome/free-solid-svg-icons';

    import {
        faArrowAltCircleLeft as farArrowAltCircleLeft,
        faCalendarAlt as farCalendarAlt,
        faCircle as farCircle,
        faGem as farGem,
        faLifeRing as farLifeRing,
        faQuestionCircle as farQuestionCircle,
        faWindowClose as farWindowClose,
    } from '@fortawesome/free-regular-svg-icons';

    import {
        faCcAmex,
        faCcMastercard,
        faCcVisa,
        faApple,
        faFacebookF,
        faFacebookMessenger,
        faFacebookSquare,
        faInstagram,
        faLinkedinIn,
        faTiktok,
        faTwitter,
        faUnity,
        faYoutube,
    } from '@fortawesome/free-brands-svg-icons';

    // brand icons
    library.add(
        faApple,
        faLinkedinIn,
        faYoutube,
        faTwitter,
        faFacebookF,
        faTiktok,
        faUnity,
        faInstagram,
        faFacebookSquare,
        faFacebookMessenger,
        faCcVisa,
        faCcMastercard,
        faCcAmex
    );

    // regular icons
    library.add(
        farLifeRing,
        farCircle,
        farArrowAltCircleLeft,
        farGem,
        farCalendarAlt,
        farWindowClose,
        farQuestionCircle
    );

    // solid icons
    library.add(
        faPlus,
        faInfoCircle,
        faTrashAlt,
        faSpinner,
        faDownload,
        faQuestionCircle,
        faCheckCircle,
        faPlusCircle,
        faCheck,
        faEnvelope,
        faUser,
        faInfo,
        faSync,
        faEye,
        faEyeSlash,
        faCopy,
        faChartLine,
        faBell,
        faBellSlash,
        faLock,
        faComment,
        faAlignLeft,
        faAngleDown,
        faAngleRight,
        faAngleLeft,
        faArrowLeft,
        faArrowRight,
        faArrowUp,
        faArrowDown,
        faArrowsAltH,
        faAd,
        faBan,
        faBookmark,
        faBriefcase,
        faBullhorn,
        faCaretDown,
        faCaretLeft,
        faCaretRight,
        faCaretUp,
        faChartBar,
        faCheckSquare,
        faChevronUp,
        faChevronDown,
        faChevronRight,
        faChevronLeft,
        faCircle,
        faCreditCard,
        faCog,
        faCogs,
        faCompressAlt,
        faCrosshairs,
        faDatabase,
        faDotCircle,
        faEdit,
        faEllipsisH,
        faExclamation,
        faExclamationCircle,
        faExclamationTriangle,
        faExpandAlt,
        faExternalLinkAlt,
        faEquals,
        faGlobe,
        faKey,
        faLayerGroup,
        faMinus,
        faPlayCircle,
        faPlug,
        faPlusSquare,
        faQuestion,
        faRocket,
        faSearch,
        faSignOutAlt,
        faSlash,
        faStar,
        faTimes,
        faTimesCircle,
        faUsersCog,
        faUpload,
        faListOl,
        faFileImage,
        faCamera,
        faShareAlt,
        faShieldAlt,
        faMobileAlt,
        faMoneyBillAlt,
        faCalendar,
        faCalendarAlt,
        faClock,
        faCodeBranch,
        faFile,
        faFileAlt,
        faImage,
        faLink,
        faDollarSign,
        faStickyNote,
        faIdBadge,
        faTh,
        faTextWidth,
        faIdCard,
        faAngleDoubleUp,
        faDraftingCompass,
        faGraduationCap,
        faChartArea,
        faTag,
        faTrash,
        faBars,
        faRedo,
        faVideo,
        faBook
    );

    export default {
        name: 'ma-icon',
        components: {
            FontAwesomeIcon,
        },
        props: {
            icon: { type: String },
            size: { type: String, default: '1x' },
            color: { type: String },
            spin: { type: Boolean, default: false },
        },
        computed: {
            classNames() {
                const classes = {
                    [`ma-${this.color}`]: true,
                };
                return classes;
            },
        },
    };
</script>

<style lang="scss" scoped>
  .ma-white {
    color: #fff;
  }
</style>
